
package dk.diku.pcsd.exam.partition;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountManagerPartitionImplService", targetNamespace = "http://partition.exam.pcsd.diku.dk/", wsdlLocation = "http://localhost:8080/partition/accountmanagerpartition?wsdl")
public class AccountManagerPartitionImplService
    extends Service
{

    private final static URL ACCOUNTMANAGERPARTITIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTMANAGERPARTITIONIMPLSERVICE_EXCEPTION;
    private final static QName ACCOUNTMANAGERPARTITIONIMPLSERVICE_QNAME = new QName("http://partition.exam.pcsd.diku.dk/", "AccountManagerPartitionImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/partition/accountmanagerpartition?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTMANAGERPARTITIONIMPLSERVICE_WSDL_LOCATION = url;
        ACCOUNTMANAGERPARTITIONIMPLSERVICE_EXCEPTION = e;
    }

    public AccountManagerPartitionImplService() {
        super(__getWsdlLocation(), ACCOUNTMANAGERPARTITIONIMPLSERVICE_QNAME);
    }

    public AccountManagerPartitionImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTMANAGERPARTITIONIMPLSERVICE_QNAME, features);
    }

    public AccountManagerPartitionImplService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTMANAGERPARTITIONIMPLSERVICE_QNAME);
    }

    public AccountManagerPartitionImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTMANAGERPARTITIONIMPLSERVICE_QNAME, features);
    }

    public AccountManagerPartitionImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountManagerPartitionImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountManagerPartitionImpl
     */
    @WebEndpoint(name = "AccountManagerPartitionImplPort")
    public AccountManagerPartitionImpl getAccountManagerPartitionImplPort() {
        return super.getPort(new QName("http://partition.exam.pcsd.diku.dk/", "AccountManagerPartitionImplPort"), AccountManagerPartitionImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountManagerPartitionImpl
     */
    @WebEndpoint(name = "AccountManagerPartitionImplPort")
    public AccountManagerPartitionImpl getAccountManagerPartitionImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://partition.exam.pcsd.diku.dk/", "AccountManagerPartitionImplPort"), AccountManagerPartitionImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTMANAGERPARTITIONIMPLSERVICE_EXCEPTION!= null) {
            throw ACCOUNTMANAGERPARTITIONIMPLSERVICE_EXCEPTION;
        }
        return ACCOUNTMANAGERPARTITIONIMPLSERVICE_WSDL_LOCATION;
    }

}
