
package dk.diku.pcsd.exam.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountManagerProxyImplService", targetNamespace = "http://proxy.exam.pcsd.diku.dk/", wsdlLocation = "http://localhost:8080/proxy/accountmanagerproxy?wsdl")
public class AccountManagerProxyImplService
    extends Service
{

    private final static URL ACCOUNTMANAGERPROXYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTMANAGERPROXYIMPLSERVICE_EXCEPTION;
    private final static QName ACCOUNTMANAGERPROXYIMPLSERVICE_QNAME = new QName("http://proxy.exam.pcsd.diku.dk/", "AccountManagerProxyImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/proxy/accountmanagerproxy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTMANAGERPROXYIMPLSERVICE_WSDL_LOCATION = url;
        ACCOUNTMANAGERPROXYIMPLSERVICE_EXCEPTION = e;
    }

    public AccountManagerProxyImplService() {
        super(__getWsdlLocation(), ACCOUNTMANAGERPROXYIMPLSERVICE_QNAME);
    }

    public AccountManagerProxyImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTMANAGERPROXYIMPLSERVICE_QNAME, features);
    }

    public AccountManagerProxyImplService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTMANAGERPROXYIMPLSERVICE_QNAME);
    }

    public AccountManagerProxyImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTMANAGERPROXYIMPLSERVICE_QNAME, features);
    }

    public AccountManagerProxyImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountManagerProxyImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountManagerProxyImpl
     */
    @WebEndpoint(name = "AccountManagerProxyImplPort")
    public AccountManagerProxyImpl getAccountManagerProxyImplPort() {
        return super.getPort(new QName("http://proxy.exam.pcsd.diku.dk/", "AccountManagerProxyImplPort"), AccountManagerProxyImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountManagerProxyImpl
     */
    @WebEndpoint(name = "AccountManagerProxyImplPort")
    public AccountManagerProxyImpl getAccountManagerProxyImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://proxy.exam.pcsd.diku.dk/", "AccountManagerProxyImplPort"), AccountManagerProxyImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTMANAGERPROXYIMPLSERVICE_EXCEPTION!= null) {
            throw ACCOUNTMANAGERPROXYIMPLSERVICE_EXCEPTION;
        }
        return ACCOUNTMANAGERPROXYIMPLSERVICE_WSDL_LOCATION;
    }

}
