
package dk.diku.pcsd.exam.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InexistentBranchException", targetNamespace = "http://proxy.exam.pcsd.diku.dk/")
public class InexistentBranchException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InexistentBranchException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InexistentBranchException_Exception(String message, InexistentBranchException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InexistentBranchException_Exception(String message, InexistentBranchException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: dk.diku.pcsd.exam.proxy.InexistentBranchException
     */
    public InexistentBranchException getFaultInfo() {
        return faultInfo;
    }

}
